### ISSUE TITLE
requests.exceptions.HTTPError: 504 Server Error: Gateway Timeout for url: https://overpass-api.de/api/interpreter

### ISSUE THREAD

**Issue by embix** [C1710/TrainCompany-tools#42]
Seems like overpass-api has a problem - not sure if that relates to the data `import_brouter.py` is sending of if they are temporarily out of order.

Sadly that is unhandled in `import_brouter.py` so we cannot fill the gaps manually.

Tried to import: [route-ceskalipa-benesovnadploucnici.zip](https://github.com/C1710/TrainCompany-tools/files/9594292/route-ceskalipa-benesovnadploucnici.zip)

**Comment by embix** [comment]
Import went through in 5th try, so it _was_ their problem. Nonetheless should the `import_brouter` script handle that kind of errors.

**Comment by C1710** [comment]
The reason why I just let it crash on these errors is that I don't want to finish with incomplete data (although it does sometimes, because when Overpass reaches the execution limit, it only returns the part it managed to finish).

If Overpass does not work (which could be because of rate limit, for example), use the `--no-overpass` option.

**Comment by C1710** [comment]
But right now it really has issues 😅
(Web requests via Overpass Turbo don't work either)

**Comment by embix** [comment]
> If Overpass does not work (which could be because of rate limit, for example), use the `--no-overpass` option.

I'll try to remember that when I encounter the problem next time.
